name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  nuke:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.103
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Nuke
      run: .\build.ps1
      shell: pwsh
